name: Publish package to GitHub Packages

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  publish:
    name: Publish package
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'corretto'
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Publish package
        run: ./gradlew publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
